name: Veldrid CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build_windows:
    runs-on: windows-latest # for DirectX

    steps:
    - uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: 9.0.x

    - name: Exclude projects
      working-directory: ./src
      run: >
        dotnet sln remove
        Veldrid.Tests.Android/Veldrid.Tests.Android.csproj

    - name: Restore dependencies
      run: dotnet restore src

    - name: Build
      run: dotnet build --no-restore src

    - name: Test
      run: dotnet test --no-build --verbosity normal src --filter "Backend=D3D11"

