name: Veldrid Generate Release

on:
  push:
    tags: ["*.*.*"]

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build_packages:
    runs-on: windows-latest # for DirectX

    steps:
    - uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: 9.0.x

    - name: Exclude projects
      working-directory: .
      run: >
        dotnet sln remove
        src/Veldrid.Tests.Android/Veldrid.Tests.Android.csproj

    - name: Restore dependencies
      run: dotnet restore .

    - name: Build
      run: dotnet build --no-restore -c Release .
      env:
        MINVER_VERSION: ${{ vars.MINVER_VERSION }}

    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal . --filter "Backend=D3D11"

    - name: Pack
      run: dotnet pack -c Release .

    - name: Push to NuGet
      env:
        SOURCE: https://api.nuget.org/v3/index.json
        API_KEY: ${{ secrets.NUGET_API_KEY }}
      if: env.SOURCE != '' || env.API_KEY != ''
      run: |
        $files = Get-ChildItem -Path . -Filter 'Sinkers.*.nupkg' -Recurse
        foreach ($file in $files) {
          dotnet nuget push $file.FullName --source ${{ env.SOURCE }} --api-key ${{ env.API_KEY }}
        }

#    - name: Generate GitHub Release
#      uses: softprops/action-gh-release@v1
#      with:
#        files: |
#          bin\Packages\Release\*.nupkg
